services:
  - type: web
    name: telegram-calendar-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_EMAIL
        sync: false
      - key: TIMEZONE
        value: Europe/Istanbul
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
